name: Feature request Form Simple
description: Suggest an idea for this project
title: "[Feature] - [Task]"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Fill out this template when requesting a new feature. Keep answers concise.

  - type: textarea
    id: task_description
    attributes:
      label: Task
      description: Description of task to be implemented.
      placeholder: |
        Example: Add a dark mode theme option that users can toggle in their settings. This will reduce eye strain for users working in low-light environments.
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List the key requirements for this feature
      placeholder: |
        - Feature needs to do x
        - Feature needs to also do y
      value: |
        - Feature needs to do x
        - Feature needs to also do y
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define clear, testable criteria for this feature (BDD-style)
      placeholder: |
        - [ ] Given I am logged in, when I navigate to settings, then I see a dark mode toggle
        - [ ] Given dark mode is enabled, when I view any page, then the color scheme is dark
      value: |
        - [ ] Given <context>, when <action>, then <expected>
        - [ ] Additional clear, testable criteria
    validations:
      required: true
